# Generated by Django 4.2.7 on 2023-12-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'User')], default=1)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fk_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.addressmodel')),
            ],
        ),
    ]
