# Generated by Django 4.2.7 on 2023-12-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('cod_voucher', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
    ]
