# Generated by Django 4.2.7 on 2023-12-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='hashed_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
